### ISSUE TITLE
Código que causo problemas en el MainActivity

### ISSUE THREAD

**Issue by alcarazolabs** [gastsail/MovieApp#1]
Buenas @gastsail bro antes seguir con el curso y enviar parámetros entre los fragments con MVVM llego el momento de probar la aplicación por que estuve muy atento a tus explicaciones la verdad son muy buenas.

Al descargarme el proyecto de este repo y al compilarlo se lanza una excepción: 
```
2021-04-16 13:32:03.271 4143-4143/com.example.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.demo, PID: 4143
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.demo/com.example.demo.MainActivity}: java.lang.IllegalStateException: Activity com.example.demo.MainActivity@a3be109 does not have a NavController set on 2131230966
        a
```
Creo que este error dice que el MainActivity no tiene un navController.. E revisado el código y en el MainActivity hay un código que en el curso no se uso ni se explico:

```
  override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        navController = Navigation.findNavController(this,R.id.nav_host_fragment)
        NavigationUI.setupActionBarWithNavController(this, navController)
    }
```
Lo que e echo a sido comentar todo eso y la aplicación ahora si se ejecuta.. ¿En que momento hay que usar ese código o ya esta obsoleto?

En el Layout del MainActivity tenemos un FragmentContainerView que ya por defecto va a cargar nuestro contenedores de fragments app:navGraph="@navigation/main_graph" ...

Otra cosa es que existe una carpeta llamada "domain" la cual la voy a renombrar como "repository".. 

Gracias.

**Comment by gastsail** [comment]
Buenas, eso se debe a que hay que setear el navcontroll en en el mainactivity para usar FragmentContainerView, en el curso hay una seccion que se llama comunicacion entre fragmentos con MVVM y ahi lo explico, por ahora para salir del apuro puedes usar <fragment> en reeemplazo de <FragmentContainerView
